[package]
name = "ab3de_internal_shared"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ab3de_engine = { workspace = true }

glam = { workspace = true }
